-- AlterTable
ALTER TABLE "MLBPitchingStats" ALTER COLUMN "ip_1" DROP NOT NULL,
ALTER COLUMN "ip_2" DROP NOT NULL,
ALTER COLUMN "bf" DROP NOT NULL,
ALTER COLUMN "gofo" DROP NOT NULL,
ALTER COLUMN "babip" DROP NOT NULL,
ALTER COLUMN "gbfb" DROP NOT NULL;
